channels:
- conda-forge
dependencies:
- python=3.10.12
- pip<=23.2.1
- pip:
  - mlflow==2.6.0
  - cloudpickle==2.2.1
  - numpy==1.25.2
  - pandas==1.5.3
  - psutil==5.9.5
  - scikit-learn==1.3.0
  - scipy==1.11.2
  - xgboost==2.0.1
name: mlflow-env
